configure.ac: link with -lm
Link with -lm to avoid the following build failure since version 0.6.0
and
https://github.com/c-icap/c-icap-server/commit/bc9f45400091b862df4bd398888c8c360c8bf9be:

/home/fabrice/buildroot/output/host/opt/ext-toolchain/bin/../lib/gcc/x86_64-buildroot-linux-gnu/13.2.0/../../../../x86_64-buildroot-linux-gnu/bin/ld: ./.libs/libicapapi.so: undefined reference to `exp'

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>